name = "pull-cork-before-reading"
compatibility_date = "2024-01-01"

[env.production]
name = "pull-cork-before-reading"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "service-worker"